Add files via upload

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -210,6 +210,50 @@ jobs:
             ansible-playbook -i inventory.txt configure-server.yml
           #  exit 1
       # Here's where you will add some code to rollback on failure   
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+
+    steps:
+      - checkout 
+      - restore_cache:
+          keys: [backend-build]
+
+      - attach_workspace:
+            at: ~/
+      # Checkout code from git
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+            cat migration.txt
+          # Run and sve the migration output
+            
+            # Your code here
+          #  exit 1
+      - run:
+          name: Send migration results to file as memstash not available
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+              then
+                ~/project/backend/migrations_dump.txt
+            fi
+#              curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+#            fi
+      
+      - persist_to_workspace:
+            root: ~/
+            paths:
+              - project/.circleci/temp/migration_output.txt 
+
+          # Your code here
+#            exit 1
+     # Here's where you will add some code to rollback on failure      
+
+
 
 workflows:
   default:
@@ -233,3 +277,5 @@ workflows:
               only: [master]    
       - configure-infrastructure:
           requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
